
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Providers from "./providers";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  manifest: "/manifest.json",
  title: "Create Next App",
  description: "Generated by create next app",
};
  
  export default function RootLayout({ children }) {


  return (
    <html lang="en">
      <body
      suppressHydrationWarning = {true}
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
       <Providers>
           {/* <NavbarWrapper /> */}
        {children}
        </Providers>
      </body>
    </html>
  //  <html lang="en">
  //     <body className={inter.className}>
  //       <Providers>{children}</Providers>
  //     </body>
  //   </html>
  );
}
